import { jsPDF } from 'jspdf';

interface VoucherData {
  voucherId: number;
  voucherCode: string;
  discount: string;
  validUntil: string;
  matchPercentage: number;
}

export async function generateVoucherPDF(voucherData: VoucherData): Promise<void> {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a5'
  });

  // Set background color
  doc.setFillColor(142, 44, 142); // #8e2c8e - primary color
  doc.rect(0, 0, 210, 148, 'F');
  
  // Add border
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(2);
  doc.rect(10, 10, 190, 128, 'S');
  
  // Add Mawadha logo placeholder (in a real implementation, you'd embed the actual logo)
  doc.setFillColor(255, 255, 255);
  doc.circle(105, 30, 15, 'F');
  
  // Set text color to white
  doc.setTextColor(255, 255, 255);
  
  // Add title
  doc.setFontSize(24);
  doc.text('MAWADHA', 105, 60, { align: 'center' });
  
  doc.setFontSize(16);
  doc.text('Be a better half', 105, 70, { align: 'center' });
  
  // Add voucher content
  doc.setFontSize(28);
  doc.text(`${voucherData.discount} COUPLE'S DINNER`, 105, 90, { align: 'center' });
  
  // Add voucher code
  doc.setFontSize(16);
  doc.text(`Voucher Code: ${voucherData.voucherCode}`, 105, 105, { align: 'center' });
  
  // Format date
  const validUntil = new Date(voucherData.validUntil);
  const formattedDate = validUntil.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  // Add valid until date
  doc.setFontSize(12);
  doc.text(`Valid until: ${formattedDate}`, 105, 115, { align: 'center' });
  
  // Add compatibility score
  doc.setFontSize(10);
  doc.text(`Compatibility Score: ${voucherData.matchPercentage}%`, 105, 125, { align: 'center' });
  
  // Add footer
  doc.setFontSize(8);
  doc.text('This voucher was generated by the Mawadha Compatibility Challenge.', 105, 135, { align: 'center' });
  
  // Mark voucher as downloaded in the database
  try {
    await fetch(`/api/vouchers/${voucherData.voucherId}/download`, {
      method: 'POST',
    });
  } catch (error) {
    console.error('Error marking voucher as downloaded:', error);
  }
  
  // Save the PDF
  doc.save(`Mawadha-Voucher-${voucherData.voucherCode}.pdf`);
}
